import { AuthProvider } from '@/context/AuthContext'
import './body.css'
import Script from 'next/script'
export const metadata = {
  title: 'SerFlix',
  description: 'Generated by students of the IUSH',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <head>
        <title>{metadata.title}</title>
        <Script src="https://kit.fontawesome.com/31d3c05807.js" crossOrigin="anonymous" strategy="afterInteractive" />
        <link rel="icon" href="/favicon.ico" />
       </head>
      <AuthProvider>
        <body>{children}</body>
      </AuthProvider>
    </html>
  );
}
